---
l: 90.0
linearAlpha: false
linearBeta: false
spinningAlpha: false
spinningBeta: false
difficulty: 1
atoms:
- 5
- 5
- 5
- 5
powerups:
- 5
- 5
- 5
- 5
molecules:
- 5
- 5
- 5
- 5
blockers:
- 5
- 5
- 5
- 5
